// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 * Create as many sidebars as you want.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  // Sidebar for the tutorial
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manually adding the 'Inspector de Elementos' category
  inspectorSidebar: [
    {
      type: 'category',
      label: 'Inspector de Elementos',
      items: [
        'inspector/index',  // El archivo index.md
        'inspector/que-es-inspector',
        'inspector/abrir-inspector',
        'inspector/examinar-css',
        'inspector/modificar-html-temporal',
        'inspector/debug-docusaurus',
      ],
    },
  ],
};

module.exports = sidebars;
